### Cadastro de Usuário
POST http://localhost:5284/api/usuarios/cadastrar
Content-Type: application/json

{
    "nome": "Alice",
    "idade": 21
}

### Listagem de Usuários
GET http://localhost:5284/api/usuarios/listar

### Buscar Usuário por ID
GET http://localhost:5284/api/usuarios/buscar/84b822ef-a217-4f3a-ae16-f5cfce885947

### Deletar Usuário por ID
DELETE http://localhost:5284/api/usuarios/deletar/baa15599-e074-4dbc-9480-654ee8346a72

### Alterar Usuário por ID
PUT http://localhost:5284/api/usuarios/alterar/aeade0b7-c86f-45b3-af6c-2be84087cb27ssssssss
Content-Type: application/json

{
    "nome": "Ygor",
    "idade": 22
}
